name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      pull-requests: write
      repository-projects: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      # - name: Test Report
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()
      #   with:
      #     name: Jest Tests
      #     path: reports/jest-*.xml
      #     reporter: jest-junit

      - name: Publish coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          report_path: coverage/lcov-report
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run tests
      #   run: npm test

      # - name: Run tests
      #   run: npx jest --coverage --coverageReporters json-summary
      # - name: Jest Coverage Comment
      #   uses: MishaKav/jest-coverage-comment@main
      #   with:
      #     coverage-summary-path: coverage/coverage-summary.json

      # - name: Generate and report coverage
      #   uses: ArtiomTr/jest-coverage-report-action@v2
      #   with:
      #     skip-step: install
      #     test-script: jest --coverage
      # coverage-file: coverage/coverage-final.json
      # base-coverage-file: coverage/coverage-final.json
